groups:
- name: trading_alerts
  rules:
  - alert: HighDrawdown
    expr: quantumsol_drawdown_percent > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High drawdown detected
      description: 'Drawdown is {{ $value }}%, which is above the 10% threshold'

  - alert: DailyLossLimit
    expr: quantumsol_daily_pnl < -2000
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Daily loss limit reached
      description: 'Daily PnL is {{ $value }}, which is below the $2000 threshold'

  - alert: AgentDown
    expr: up{job="quantumsol"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: QuantumSol Agent Down
      description: 'The QuantumSol agent is down or not responding'

  - alert: HighErrorRate
    expr: rate(quantumsol_errors_total[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High error rate detected
      description: 'Error rate is {{ $value }} errors per second'

  - alert: LowLiquidity
    expr: quantumsol_liquidity_ratio < 0.5
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: Low liquidity detected
      description: 'Liquidity ratio is {{ $value }}, which is below the 0.5 threshold'
