global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'quantumsol'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['agent:8000']
        labels:
          service: 'quantumsol-agent'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

rule_files:
  - 'alerts.yml'
